### ISSUE TITLE
Fix Azire VPN Host interactions

### ISSUE THREAD

**Issue by andrebreis** [MattSkala/cloudomate#6]
It seems that VPN is very important in order to not get banned from VPS hosts

So we'll need to fix this one too

**Comment by andrebreis** [comment]
I'm attributing this mistake to python versions - it's working!

**Comment by MattSkala** [comment]
When trying to purchase the VPN with `cloudomate vpn purchase azirevpn`, I get the following exception:
```
Traceback (most recent call last):
  File "/usr/local/bin/cloudomate", line 11, in <module>
    sys.exit(execute())
  File "/usr/local/lib/python3.7/site-packages/cloudomate/cmdline.py", line 79, in execute
    args.func(args)
  File "/usr/local/lib/python3.7/site-packages/cloudomate/cmdline.py", line 300, in purchase
    _purchase_vpn(provider, user_settings, args)
  File "/usr/local/lib/python3.7/site-packages/cloudomate/cmdline.py", line 385, in _purchase_vpn
    _register(provider, options[0], user_settings)
  File "/usr/local/lib/python3.7/site-packages/cloudomate/cmdline.py", line 500, in _register
    provider_instance.purchase(wallet, vps_option)
  File "/usr/local/lib/python3.7/site-packages/cloudomate/hoster/vpn/azirevpn.py", line 98, in purchase
    page = self._order()
  File "/usr/local/lib/python3.7/site-packages/cloudomate/hoster/vpn/azirevpn.py", line 157, in _order
    form["package"] = "1"
  File "/usr/local/lib/python3.7/site-packages/mechanicalsoup/form.py", line 225, in __setitem__
    return self.set(name, value)
  File "/usr/local/lib/python3.7/site-packages/mechanicalsoup/form.py", line 259, in set
    getattr(self, "set_" + func)({name: value})
  File "/usr/local/lib/python3.7/site-packages/mechanicalsoup/form.py", line 172, in set_radio
    "No input radio named %s with choice %s" % (name, value)
mechanicalsoup.utils.LinkNotFoundError: No input radio named package with choice 1
```
